# Generated by Django 5.1.7 on 2025-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
