# Generated by Django 5.1.7 on 2025-03-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
