# Generated by Django 5.1.7 on 2025-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_packages_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
