# Generated by Django 5.1.7 on 2025-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=10, unique=True)),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
    ]
